name: 'Terraform-Plan-Infra-PlanV02100'

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'feature/*'
    paths:
      - './**'
      - '.github/workflows/TF_PlanV03.yml'

env:
  WORKING_DIR: "./"
  TF_VER: 1.4.6
  BACKEND_FILE: backend.tf
  #
  
jobs:
  tf-plan:
    timeout-minutes: ${{ fromJSON(vars.JOB_TIMEOUT_MINUTES_SHORT) }}
    name: 'terraform: init,validate,plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Run> terraform validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color

      - name: Check for "terraform plan" failure
        if: steps.tf-plan.outputs.exitcode == 1
        run: exit 1

    outputs:
      tf-plan-exit-code: ${{ steps.tf-plan.outputs.exitcode }}