name: 'Push on Dev env'

on:
  push:
    branches:
      - feature_AS127_dev_100

env:
  TF_LOG: INFO
  TF_INPUT: false

permissions:
    id-token: write
    contents: read

jobs:
  terraform:
    name: 'Terraform Push'
    runs-on: ubuntu-latest

    # Use the Bash shell
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Log into Azure with OIDC integration if branch is feature_AS127_dev_100
    - name: 'Az CLI login for feature_AS127_dev_100 branch' 
      if: github.ref == 'refs/heads/feature_AS127_dev_100'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    # Run Terraform init for Main branch
    - name: Terraform Init for feature_AS127_dev_100 branch
      id: init-main
      if: github.ref == 'refs/heads/feature_AS127_dev_100'
      env:
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform init"

    # Run Terraform apply if branch is main
    - name: Terraform Apply for feature_AS127_dev_100 branch
      if: github.ref == 'refs/heads/feature_AS127_dev_100'
      id: apply
      env:
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform apply -auto-approve

    # Run a Terraform validate
    - name: Terraform validate
      id: validate
      env:
        AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform validate -no-color